stages:
  get_data:
    cmd: python src\get_data.py --config=params.yaml
    deps:
    - src\read_params.py
    - src\get_data.py
    - src\utils\preprocessing.py
    - data\train
    - data\val
  
  train_evaluate:
    cmd: python src\train_evaluate.py --config=params.yaml
    deps:
    - src\get_data.py
    - src\train_evaluate.py
    - src\display\showOutput.py
    - src\model\train.py
    - src\model\build.py
    - src\model\sample.py
    - src\model\loss\losses.py
    outs:
    - saved_model\generator\gen.h5
    - saved_model\discriminator\disc.h5