stages:
  get_data:
    cmd: python src\get_data.py --config=params.yaml
    deps:
    - src\read_params.py
    - src\get_data.py
    - src\utils\preprocessing.py
    - data\train\*.png
    - data\val\*.png
    outs:
    - train_dataset
    - test_dataset