base:
  project: Sketch_To_ColorImg

data_path:
  colorgram_path: data\colorgram
  train_path: data\train
  val_path: data\val

data_load:
  batch_size: 4
  buffer_size: 4500
  img_width: 256
  img_height: 256

model:
  output_channels: 3
  epochs: 100

loss:
  lambda: 100

evaluate:
  final_sample: 10

model_dir:
  generator: saved_models\generator\gen.h5
  discriminator: saved_models\discriminator\disc.h5

generate_output:
  output_path: Results